### ISSUE TITLE
Can we add a new `Provider` component with hook?

### ISSUE THREAD

**Issue by hideokamoto** [capacitor-community/react-hooks#36]
Now I'm contributing to the Stripe plugin for Capacitor.
https://github.com/capacitor-community/stripe

And I would like to publish new useful utils for this plugin to React developers.
But for now, I'm using a `Provider` component like this.
https://github.com/capacitor-community/stripe/blob/demo/react/demo/react/src/fixtures/Provider.tsx

Can we add these types of files into your project as `@capacitor-community/stripe-react`?
Or should we make only React hook?
Thanks!

**Comment by elylucas** [comment]
Hi @hideokamoto,

For this repo, I'd prefer to keep it targeted to just the core capacitor plugins as the core team doesn't plan on supporting bindings for libraries like React directly in the capacitor repo. 

For other community plugins like your stripe plugin, you can put the bindings directly in your project and publish them to npm under @capactior-community/stripe-react. 

Let me know if that makes sense.
